//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientConsultationArticleWCF.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webService/", ConfigurationName="ServiceReference1.ConsultationArticlesWebService")]
    public interface ConsultationArticlesWebService {
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webService/ConsultationArticlesWebService/setArticlesRequest", ReplyAction="http://webService/ConsultationArticlesWebService/setArticlesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClientConsultationArticleWCF.ServiceReference1.setArticlesResponse setArticles(ClientConsultationArticleWCF.ServiceReference1.setArticlesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webService/ConsultationArticlesWebService/setArticlesRequest", ReplyAction="http://webService/ConsultationArticlesWebService/setArticlesResponse")]
        System.Threading.Tasks.Task<ClientConsultationArticleWCF.ServiceReference1.setArticlesResponse> setArticlesAsync(ClientConsultationArticleWCF.ServiceReference1.setArticlesRequest request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webService/ConsultationArticlesWebService/getAllArticlesRequest", ReplyAction="http://webService/ConsultationArticlesWebService/getAllArticlesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClientConsultationArticleWCF.ServiceReference1.getAllArticlesResponse getAllArticles(ClientConsultationArticleWCF.ServiceReference1.getAllArticlesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webService/ConsultationArticlesWebService/getAllArticlesRequest", ReplyAction="http://webService/ConsultationArticlesWebService/getAllArticlesResponse")]
        System.Threading.Tasks.Task<ClientConsultationArticleWCF.ServiceReference1.getAllArticlesResponse> getAllArticlesAsync(ClientConsultationArticleWCF.ServiceReference1.getAllArticlesRequest request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webService/ConsultationArticlesWebService/getArticlesRequest", ReplyAction="http://webService/ConsultationArticlesWebService/getArticlesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClientConsultationArticleWCF.ServiceReference1.getArticlesResponse getArticles(ClientConsultationArticleWCF.ServiceReference1.getArticlesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webService/ConsultationArticlesWebService/getArticlesRequest", ReplyAction="http://webService/ConsultationArticlesWebService/getArticlesResponse")]
        System.Threading.Tasks.Task<ClientConsultationArticleWCF.ServiceReference1.getArticlesResponse> getArticlesAsync(ClientConsultationArticleWCF.ServiceReference1.getArticlesRequest request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webService/ConsultationArticlesWebService/getLocalSearchRequest", ReplyAction="http://webService/ConsultationArticlesWebService/getLocalSearchResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClientConsultationArticleWCF.ServiceReference1.getLocalSearchResponse getLocalSearch(ClientConsultationArticleWCF.ServiceReference1.getLocalSearchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webService/ConsultationArticlesWebService/getLocalSearchRequest", ReplyAction="http://webService/ConsultationArticlesWebService/getLocalSearchResponse")]
        System.Threading.Tasks.Task<ClientConsultationArticleWCF.ServiceReference1.getLocalSearchResponse> getLocalSearchAsync(ClientConsultationArticleWCF.ServiceReference1.getLocalSearchRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webService/")]
    public partial class article : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int dislikesField;
        
        private int likesField;
        
        private string texteField;
        
        private string titreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int dislikes {
            get {
                return this.dislikesField;
            }
            set {
                this.dislikesField = value;
                this.RaisePropertyChanged("dislikes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int likes {
            get {
                return this.likesField;
            }
            set {
                this.likesField = value;
                this.RaisePropertyChanged("likes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string texte {
            get {
                return this.texteField;
            }
            set {
                this.texteField = value;
                this.RaisePropertyChanged("texte");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string titre {
            get {
                return this.titreField;
            }
            set {
                this.titreField = value;
                this.RaisePropertyChanged("titre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setArticles", WrapperNamespace="http://webService/", IsWrapped=true)]
    public partial class setArticlesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webService/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("liste", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClientConsultationArticleWCF.ServiceReference1.article[] liste;
        
        public setArticlesRequest() {
        }
        
        public setArticlesRequest(ClientConsultationArticleWCF.ServiceReference1.article[] liste) {
            this.liste = liste;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setArticlesResponse", WrapperNamespace="http://webService/", IsWrapped=true)]
    public partial class setArticlesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webService/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public setArticlesResponse() {
        }
        
        public setArticlesResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllArticles", WrapperNamespace="http://webService/", IsWrapped=true)]
    public partial class getAllArticlesRequest {
        
        public getAllArticlesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllArticlesResponse", WrapperNamespace="http://webService/", IsWrapped=true)]
    public partial class getAllArticlesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webService/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClientConsultationArticleWCF.ServiceReference1.article[] @return;
        
        public getAllArticlesResponse() {
        }
        
        public getAllArticlesResponse(ClientConsultationArticleWCF.ServiceReference1.article[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getArticles", WrapperNamespace="http://webService/", IsWrapped=true)]
    public partial class getArticlesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webService/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string value;
        
        public getArticlesRequest() {
        }
        
        public getArticlesRequest(string value) {
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getArticlesResponse", WrapperNamespace="http://webService/", IsWrapped=true)]
    public partial class getArticlesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webService/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClientConsultationArticleWCF.ServiceReference1.article[] @return;
        
        public getArticlesResponse() {
        }
        
        public getArticlesResponse(ClientConsultationArticleWCF.ServiceReference1.article[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getLocalSearch", WrapperNamespace="http://webService/", IsWrapped=true)]
    public partial class getLocalSearchRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webService/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string value;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webService/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("liste", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClientConsultationArticleWCF.ServiceReference1.article[] liste;
        
        public getLocalSearchRequest() {
        }
        
        public getLocalSearchRequest(string value, ClientConsultationArticleWCF.ServiceReference1.article[] liste) {
            this.value = value;
            this.liste = liste;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getLocalSearchResponse", WrapperNamespace="http://webService/", IsWrapped=true)]
    public partial class getLocalSearchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webService/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClientConsultationArticleWCF.ServiceReference1.article[] @return;
        
        public getLocalSearchResponse() {
        }
        
        public getLocalSearchResponse(ClientConsultationArticleWCF.ServiceReference1.article[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConsultationArticlesWebServiceChannel : ClientConsultationArticleWCF.ServiceReference1.ConsultationArticlesWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultationArticlesWebServiceClient : System.ServiceModel.ClientBase<ClientConsultationArticleWCF.ServiceReference1.ConsultationArticlesWebService>, ClientConsultationArticleWCF.ServiceReference1.ConsultationArticlesWebService {
        
        public ConsultationArticlesWebServiceClient() {
        }
        
        public ConsultationArticlesWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsultationArticlesWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultationArticlesWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultationArticlesWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientConsultationArticleWCF.ServiceReference1.setArticlesResponse ClientConsultationArticleWCF.ServiceReference1.ConsultationArticlesWebService.setArticles(ClientConsultationArticleWCF.ServiceReference1.setArticlesRequest request) {
            return base.Channel.setArticles(request);
        }
        
        public int setArticles(ClientConsultationArticleWCF.ServiceReference1.article[] liste) {
            ClientConsultationArticleWCF.ServiceReference1.setArticlesRequest inValue = new ClientConsultationArticleWCF.ServiceReference1.setArticlesRequest();
            inValue.liste = liste;
            ClientConsultationArticleWCF.ServiceReference1.setArticlesResponse retVal = ((ClientConsultationArticleWCF.ServiceReference1.ConsultationArticlesWebService)(this)).setArticles(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientConsultationArticleWCF.ServiceReference1.setArticlesResponse> ClientConsultationArticleWCF.ServiceReference1.ConsultationArticlesWebService.setArticlesAsync(ClientConsultationArticleWCF.ServiceReference1.setArticlesRequest request) {
            return base.Channel.setArticlesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientConsultationArticleWCF.ServiceReference1.setArticlesResponse> setArticlesAsync(ClientConsultationArticleWCF.ServiceReference1.article[] liste) {
            ClientConsultationArticleWCF.ServiceReference1.setArticlesRequest inValue = new ClientConsultationArticleWCF.ServiceReference1.setArticlesRequest();
            inValue.liste = liste;
            return ((ClientConsultationArticleWCF.ServiceReference1.ConsultationArticlesWebService)(this)).setArticlesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientConsultationArticleWCF.ServiceReference1.getAllArticlesResponse ClientConsultationArticleWCF.ServiceReference1.ConsultationArticlesWebService.getAllArticles(ClientConsultationArticleWCF.ServiceReference1.getAllArticlesRequest request) {
            return base.Channel.getAllArticles(request);
        }
        
        public ClientConsultationArticleWCF.ServiceReference1.article[] getAllArticles() {
            ClientConsultationArticleWCF.ServiceReference1.getAllArticlesRequest inValue = new ClientConsultationArticleWCF.ServiceReference1.getAllArticlesRequest();
            ClientConsultationArticleWCF.ServiceReference1.getAllArticlesResponse retVal = ((ClientConsultationArticleWCF.ServiceReference1.ConsultationArticlesWebService)(this)).getAllArticles(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientConsultationArticleWCF.ServiceReference1.getAllArticlesResponse> ClientConsultationArticleWCF.ServiceReference1.ConsultationArticlesWebService.getAllArticlesAsync(ClientConsultationArticleWCF.ServiceReference1.getAllArticlesRequest request) {
            return base.Channel.getAllArticlesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientConsultationArticleWCF.ServiceReference1.getAllArticlesResponse> getAllArticlesAsync() {
            ClientConsultationArticleWCF.ServiceReference1.getAllArticlesRequest inValue = new ClientConsultationArticleWCF.ServiceReference1.getAllArticlesRequest();
            return ((ClientConsultationArticleWCF.ServiceReference1.ConsultationArticlesWebService)(this)).getAllArticlesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientConsultationArticleWCF.ServiceReference1.getArticlesResponse ClientConsultationArticleWCF.ServiceReference1.ConsultationArticlesWebService.getArticles(ClientConsultationArticleWCF.ServiceReference1.getArticlesRequest request) {
            return base.Channel.getArticles(request);
        }
        
        public ClientConsultationArticleWCF.ServiceReference1.article[] getArticles(string value) {
            ClientConsultationArticleWCF.ServiceReference1.getArticlesRequest inValue = new ClientConsultationArticleWCF.ServiceReference1.getArticlesRequest();
            inValue.value = value;
            ClientConsultationArticleWCF.ServiceReference1.getArticlesResponse retVal = ((ClientConsultationArticleWCF.ServiceReference1.ConsultationArticlesWebService)(this)).getArticles(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientConsultationArticleWCF.ServiceReference1.getArticlesResponse> ClientConsultationArticleWCF.ServiceReference1.ConsultationArticlesWebService.getArticlesAsync(ClientConsultationArticleWCF.ServiceReference1.getArticlesRequest request) {
            return base.Channel.getArticlesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientConsultationArticleWCF.ServiceReference1.getArticlesResponse> getArticlesAsync(string value) {
            ClientConsultationArticleWCF.ServiceReference1.getArticlesRequest inValue = new ClientConsultationArticleWCF.ServiceReference1.getArticlesRequest();
            inValue.value = value;
            return ((ClientConsultationArticleWCF.ServiceReference1.ConsultationArticlesWebService)(this)).getArticlesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientConsultationArticleWCF.ServiceReference1.getLocalSearchResponse ClientConsultationArticleWCF.ServiceReference1.ConsultationArticlesWebService.getLocalSearch(ClientConsultationArticleWCF.ServiceReference1.getLocalSearchRequest request) {
            return base.Channel.getLocalSearch(request);
        }
        
        public ClientConsultationArticleWCF.ServiceReference1.article[] getLocalSearch(string value, ClientConsultationArticleWCF.ServiceReference1.article[] liste) {
            ClientConsultationArticleWCF.ServiceReference1.getLocalSearchRequest inValue = new ClientConsultationArticleWCF.ServiceReference1.getLocalSearchRequest();
            inValue.value = value;
            inValue.liste = liste;
            ClientConsultationArticleWCF.ServiceReference1.getLocalSearchResponse retVal = ((ClientConsultationArticleWCF.ServiceReference1.ConsultationArticlesWebService)(this)).getLocalSearch(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientConsultationArticleWCF.ServiceReference1.getLocalSearchResponse> ClientConsultationArticleWCF.ServiceReference1.ConsultationArticlesWebService.getLocalSearchAsync(ClientConsultationArticleWCF.ServiceReference1.getLocalSearchRequest request) {
            return base.Channel.getLocalSearchAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientConsultationArticleWCF.ServiceReference1.getLocalSearchResponse> getLocalSearchAsync(string value, ClientConsultationArticleWCF.ServiceReference1.article[] liste) {
            ClientConsultationArticleWCF.ServiceReference1.getLocalSearchRequest inValue = new ClientConsultationArticleWCF.ServiceReference1.getLocalSearchRequest();
            inValue.value = value;
            inValue.liste = liste;
            return ((ClientConsultationArticleWCF.ServiceReference1.ConsultationArticlesWebService)(this)).getLocalSearchAsync(inValue);
        }
    }
}
